version: "2"
services:
  db:
   image: postgres
  web:
   build: .
   volumes:
     - .:/code
   ports:
     - "9000:9000"
   expose:
     - 9000
   depends_on:
     - db
   command: /bin/bash -c "pip install -r requirements.txt && exec invoke run_dev"